language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - export nanomsgver=0.5-beta
  - export nanomsgbuild=`mktemp -d`
  - pushd $nanomsgbuild
  - wget http://download.nanomsg.org/nanomsg-${nanomsgver}.tar.gz
  - tar xfz nanomsg-${nanomsgver}.tar.gz
  - cd nanomsg-${nanomsgver}
  - ./configure
  - make
  - sudo make install
  - popd
install:
  - cpanm .
  - perl Makefile.PL
  - make
script:
  - make test
