language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - export nanomsgver=0.8-beta
  - export nanomsgbuild=`mktemp -d`
  - pushd $nanomsgbuild
  - wget https://github.com/nanomsg/nanomsg/releases/download/0.8-beta/nanomsg-${nanomsgver}.tar.gz
  - tar xfz nanomsg-${nanomsgver}.tar.gz
  - cd nanomsg-${nanomsgver}
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - popd
install:
  - cpanm Devel::CheckLib
  - cpanm -v --installdeps .
  - perl Makefile.PL
  - make
script:
  - make test
